# Generated by Django 2.0.7 on 2018-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to='post'),
            preserve_default=False,
        ),
    ]
